### ISSUE TITLE
Administration > Ne pas pouvoir oublier la bonne réponse dans la liste des réponses proposé

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#1]
Ajout automatique de la bonne réponse si elle est oublié dans la liste des propositions de réponse pour une question.

**Comment by Evan-Rousseau** [comment]
Je prends en charge

**Comment by Evan-Rousseau** [comment]
Lors de l'ajout d'une question ou l'édition d'une question, si la bonne réponse n'est pas sélectionnée dans les possibilités de réponse celle-ci est ajoutée automatiquement.
