### ISSUE TITLE
Bug report > Affichage des images dans les questions si mediaurl n'est pas renseigné

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#38]

**Comment by vincentkollebolle** [comment]
Piste de réflexion : 
L'image vient de l'administrateur du quizz /!\ NTU 
peut être faudrait il recréé une image à partir de celle qu'il ou elle à uploader. Ce qui nous permettrait même au passage
de wartermarker nos images ou d'en faire des thumbnail et d'en créé des versions plus "légère"...
Qqls pistes de documentation qui semblent pertinentes : 
- https://symfonycasts.com/screencast/symfony-uploads/thumbnailing
- https://symfonycasts.com/screencast/symfony-uploads/flysystem-imagine-bundle

**Comment by vincentkollebolle** [comment]
Je pense qu'il faudrait plutôt lors de l'affichage des images utiliser le helper twig asset(). 
https://symfony.com/doc/current/components/asset.html

**Comment by SeeRak** [comment]
Utilisation de PathPackage & StaticVersionStrategy

Initialisation : $package = new PathPackage('/uploads', new StaticVersionStrategy(''));
Utilisation : $question->setMediaurl($package->getUrl($file_name));

**Comment by SeeRak** [comment]
Création d'une seconde image avec ajout du watermark + compression de l'image
