### ISSUE TITLE
DeadCode : Dans QuizzController : methode quizzNextQuestion appel à méthode findByQuizz non existente.  

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#55]

**Comment by Grujj** [comment]
La méthode findByQuizz existe bien. C'est l'implémentation d'une méthode d'EntityRepository qui n'est pas reconnu par VSCode mais qui est bien appelé dans le code.

**Comment by vincentkollebolle** [comment]
Désormais la bonne pratique dans symfony pour fetch des objets depuis le répository est la suivante : 
```
$products = $repository->findBy(
    ['name' => 'Keyboard'],
    ['price' => 'ASC']
);
```

Par le passer (mais cela est toujours utilisable) on avait la possibilité de passer par des méthodes _magiques_ qui prenait la forme : findBy-Attribut- ou attribut était un attribut de l'entité voulu . 
Exemple j'ai une entité Fruit avec une propriété type 
je pouvais faire findByType() 
Bravo @Grujj
