### ISSUE TITLE
Home à transformer en redirection vers quizz pour raison de SEO. 

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#56]
**Scenario** : Un utilisateur qui consulte la route / ou la route /quizz arrive sur la même page. 
**Given**: Un utilisateur demande la page / 
**or** : Un utilisateur demande la page /quizz
**When** : Il accède à la page 
**Then**:  il est redirigé vers la route /quizz.

**Comment by vincentkollebolle** [comment]
Je propose que l'on mette en place une  nouvelle route /home qui rediregera vers la route /quizz.

**Comment by AbdelhakBLD** [comment]
J'ai mis en place une redirection de route de / vers /quizz.
[voir commit ](https://github.com/vincentkollebolle/quizzpoledance/commit/b9234803ebbab232e8dca4020bc1cbc35315924b)
