### ISSUE TITLE
Le quizz est trop long trouvé une solution à ça

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#58]

**Comment by YounesHarrat** [comment]
Fix =>
En tant que : Joueur 
je veux : lancer un quizz avec un nombre de question limité, arbitrairement => 25 questions
afin de : d'effectuer un quizz que le joueur ne considèrera pas trop long.

Solution => QuestionRepository => findAll => setMaxRequest(25).

Amélioration => 
En tant que : Joueur 
je veux : lancer un quizz avec possibilité de choisir le nombre de question
afin de : d'effectuer un quizz que le joueur ne considèrera pas trop long.

**Comment by vincentkollebolle** [comment]
Option 1 : Arbitrairement on tire 25 question aux hasard parmi toutes les question 
Option 2 : Le joueur avant de commencer défini si il veut jouer en mode **débutant** (15 questions) en mode **intermédiaire** (25 questions) et **avancé** (50 questions).

**Comment by vincentkollebolle** [comment]
L'option validé est la 2 !

**Comment by YounesHarrat** [comment]
Si difficulty n'existe pas en bdd => make migrations & maj bdd
