### ISSUE TITLE
ToDiscuss > piste SEO friendly implémenter un slug pour les question ? 

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#59]

**Comment by vincentkollebolle** [comment]
Proposition : 
1. Rajouter une attribut "slug" dans la classe de l'entité 
2. Utiliser ce slug pour trouver l'enregistrement dans les routes qui le nécessitent. 
3. Utiliser pour cela le ParamConverter.
4. Utiliser StofDoctrineExtensionsBundle pour générer automatiquement les slug à partir
     du title des entités.

**Comment by vincentkollebolle** [comment]
https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html

**Comment by vincentkollebolle** [comment]
https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html

**Comment by AbdelhakBLD** [comment]
Problème rencontrer #91 mais contourné.
