### ISSUE TITLE
Renommer l'entité Player en Administrator

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#62]

**Comment by tgillme** [comment]
L'entité Player a été renommée en Administrator.

**Comment by tgillme** [comment]
La fonction newsletter n'est plus appelée et a été supprimée.

    /**
     * @Route("/newsletter", name="newsletter")
     */
    public function newsletter(Request $request)
    {
        $player = new Administrator();
        $repository = $this->getDoctrine()->getRepository(Administrator::class);
        $players = $repository->findAll();

        $form = $this->createFormBuilder($player)
            ->add(
                'email',
                EmailType::class,
                [
                    'help' => 'Donnez votre e-mail et soyez informé.e lors de la sortie du quizz !',
                ]
            )
            ->add('save', SubmitType::class, ['label' => 'Prevenez-moi !'])
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // $form->getData() holds the submitted values
            // but, the original `$task` variable has also been updated
            $player = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($player);
            $entityManager->flush();

            //usage du flashbag ;) 
            $this->addFlash(
                'success',
                'Vous serez notifié.e des que le quizz est en ligne !'
            );

            return $this->redirectToRoute('quizz');
        }

        return $this->render('quizz/index.html.twig', [
            'form' => $form->createView(),
            'players' => $players
        ]);
    }

**Comment by tgillme** [comment]
Le fichier décrivant les fixtures a également été modifié.
