### ISSUE TITLE
Calcul des points 

### ISSUE THREAD

**Issue by jingwen-pourpoint** [vincentkollebolle/quizzpoledance#69]
Premier cas:
- Réponse 1 mauvaise réponse, message -50pts, total = 0pts
- Réponse 2 mauvaise réponse, message -50pts, total = 0pts
- Réponse 3 bonne réponse, message +100pts, total =100pts

Deuxième cas:
- Réponse 1 bonne réponse, message +100pts, total =100pts
- Réponse 2 mauvaise réponse, message -50pts, total = 50pts
- Réponse 3 mauvaise réponse, message -50pts, total = 0pts

Pour le même nombre de bonne et mauvaise réponse, on a un résultat différent. Si un score négatif n'est pas souhaité, il faudrait que ce soit uniquement à la fin du quizz

**Comment by ChercheurSwifer** [comment]
Fonctionnel.
