### ISSUE TITLE
Les questions ne sont pas affichées aléatoirement.

### ISSUE THREAD

**Issue by UnluckyNomad** [vincentkollebolle/quizzpoledance#70]
Les questions apparaissent toujours dans le même ordre, même après une actualisation ou en démarrant à nouveau le quiz.

**Comment by vincentkollebolle** [comment]
http://www.lephpfacile.com/manuel-php/function.shuffle.php

**Comment by vincentkollebolle** [comment]
Warning : /!\ Keep It Simple Stupid ;)
