### ISSUE TITLE
Bug > Usage du ParamConverter pour recherche de question à partir du "slug" impossible

### ISSUE THREAD

**Issue by vincentkollebolle** [vincentkollebolle/quizzpoledance#91]
Lors de l'utilisation du ParamConverter dans la route quizz_question pour la recherche automatique d'une question à partir de son "slug", symfony semble perdre les pédale et ne trouve la question recherchée.

**Comment by AbdelhakBLD** [comment]
Avec ce bout de code de contrôleur.

`/**
     * @Route("/quizz/{id}/question/{slug}", name="quizz_question")
     * @Entity("question", expr="repository.find(slug)")
     * @Entity("quizz", expr="repository.find(id)")
     */
    public function quizzQuestion(
        Request $request,
        Quizz $quizz,
        Question $question,
    ) {
`

On obtient cette erreur :
`App\Entity\Question object not found by the @Entity annotation. The expression "repository.find(slug)" returned null`

**Comment by AbdelhakBLD** [comment]
workaround / contournement : 

Pour contourner l'erreur j'ai dû utiliser le repository à partir du slug écrit à la main. 

`/**
     * @Route("/quizz/{id}/question/{slug}", name="quizz_question")
     * @Entity("quizz", expr="repository.find(id)")
     */
    public function quizzQuestion(
        Request $request,
        Quizz $quizz,
        $slug,
    ) {
        $questionRepository = $this->getDoctrine()->getRepository(Question::class);
        $question = $questionRepository->findOneBySlug($slug);
`
