### ISSUE TITLE
Empêcher les doublons de playernames

### ISSUE THREAD

**Issue by jingwen-pourpoint** [vincentkollebolle/quizzpoledance#95]
![image](https://user-images.githubusercontent.com/68198133/126498651-76874e4a-01a9-4369-b39b-a85e0734596d.png)

**Comment by AbdelhakBLD** [comment]
Je ferme le ticket, car résolu par @jingwen-pourpoint par ce [commit](https://github.com/vincentkollebolle/quizzpoledance/commit/f50650cf7a72e9f8a24d1ab257c3e29c5e40abc6).
