### ISSUE TITLE
Dans le classement le niveau n'est pas calculé selon le nombre de question du quizz

### ISSUE THREAD

**Issue by YounesHarrat** [vincentkollebolle/quizzpoledance#97]
Exemple:
le niveau est calculé ainsi =>
< 500 novice
< 2000 adepte
< 4000 avancé
< 8000 expert

User A fait un quizz de 15 questions . avec 900 points, il a un niveau adepte.
User B fait un quizz de 50 questions avec 1900 points , il a un niveau adepte.

Issue: un quizz de 15 questions n'atteindra jamais le niveau expert même si il répond juste a toute les questions de ce quizz.

Proposition => adapté selon la difficulté du quizz

le niveau est calculé ainsi => 

quizz->difficulty ( 15 | 25 | 50 )
factor = difficulty / 15 => 
factor = [ 1 | 1.667 | 3.333 ]

novice < 250 * factor   => < [ 250 | 416 | 833 ]
adepte < 500 * factor => < [ 500 | 833 | 1666 ]
avancé < 1000  * factor => < [ 1000 | 1667 | 3333 ]
expert < 2500  * factor => < [ 2500 | 4167 | 8332 ]

**Comment by vincentkollebolle** [comment]
validé :)
